### ISSUE TITLE
GL-119 bugs

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#14]
it treats modded grenades based on a frag grenade as frag grenades (IG-119) either remove it taking them or make them actually have the modded effects

reloading it while it is full still consumes grenades

make it set your 7.62 to 1 if you have none while holding it so it can be reloaded without 7.62 ammo

**Comment by galaxy119** [comment]
TODO: 
 - Make modded grenades used in the GL explode with their modded effects.
 - Make modded grenades ignorable by the GL.
 - Config option to switch between the above functions
 - Update reload override to new CustomWeapon standard.
 - Make sure not to consume grenades if reloading doesn't do anything.
 - Make sure players always have 1 of the ammo type used by a : CustomWeapon class because handling reloads internally.
 - Make CustomWeapons use an internal ammo type instead of the default, to avoid situations like: Being able to tranq someone 30 times due to having 30 USP rounds.

**Comment by galaxy119** [comment]
- Make sure players always have 1 of the ammo type used by a : CustomWeapon class because handling reloads internally.
 - Make CustomWeapons use an internal ammo type instead of the default, to avoid situations like: Being able to tranq someone 30 times due to having 30 USP rounds.
 
 should be re-made as a feature request on the EXILED github.
 Everything else above is implemented.
