### ISSUE TITLE
1499 bug yet again .......

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#19]
nuke patch broke again
![obrazek](https://user-images.githubusercontent.com/53602251/109267111-5a4d8280-7809-11eb-8474-38953fa4c760.png)
also suggestion: make 1499 cooldown separate from 268 cooldown

add a config option to change it

config option to reset time on death

**Comment by galaxy119** [comment]
This *should* be fixed now.. But feel free to re-open the ticket if not. If you can, try and find a reliable way to replicate the bug so that I can test properly.

As for the second part of this port, it really should be it's own feature request, but I'm not actually sure if we *can* change/bypass the 268 cooldown, it may be partially controlled client side.
