### ISSUE TITLE
more spawn location customization

### ISSUE THREAD

**Issue by ZWRh3** [Exiled-Team/CustomItems#24]
offset (needs to account for room angle)

rotation

Structures  - https://en.scpslgame.com/index.php?title=Locations

**Comment by galaxy119** [comment]
It's virtually impossible to be able to define rooms for spawn locations, this was the original intent, however because room rotation is not always the same, it's virtually impossible to ensure items actually spawn where they should, especially if using offsets. Some rooms would be save to just spawn in the center of (like LCZ hallways/junction rooms) but they are unnamed, or multiple of the same type of room will have the same name.
