### ISSUE TITLE
C4 grenades not stick to the surface

### ISSUE THREAD

**Issue by Kicpro** [Exiled-Team/CustomItems#58]
Hi, the c4 is not sticking to the walls etc.
Heres the video that shows that up:
https://www.youtube.com/watch?v=k8d6K6ymqe0&ab_channel=Kicpro
(and yes, I have this option enabled in the config)
and i dont get any errors in the console

**Comment by joker-119** [comment]
The bug report template exists for a reason, but since you choose not to use it, I need you to provide the following information:

1. A copy of the server logs file.
2. A copy of your plugin config file, and the CustomItems config file.
3. The results of the ``show plugins`` command in the server console.
